### ISSUE TITLE
立个 flag，新年前更新一个新版本

### ISSUE THREAD

**Issue by little-snow-fox** [little-snow-fox/react-native-wechat-lib#208]
请各位在此留言希望新增的功能或者需要解决的问题，我尽量处理。

**Comment by zwang62** [comment]
您真是我哥，您再不立FLAG我都打算fock库重写了。

**Comment by little-snow-fox** [comment]
> 您真是我哥，您再不立FLAG我都打算fork库重写了。
希望有能力的大佬也能提交下 PR，光靠我一个人维护的话每次个版本的迭代周期有点久，因为最近没这方面的开发任务，所以要专门抽时间升级测试和维护

**Comment by zwang62** [comment]
安卓代码混淆后会造成部分弹窗无法弹出，例如第三方消息的弹窗，例如share到朋友列表页面以后，无法继续操作
需要在proguard.cfg 中，增加如下代码，您可以加到readme里面去
-keep class com.tencent.mm.opensdk.** {
*;
}

-keep class com.tencent.wxop.** {
*;
}

-keep class com.tencent.mm.sdk.** {
*;
}

**Comment by little-snow-fox** [comment]
> 安卓代码混淆后会造成部分弹窗无法弹出，例如第三方消息的弹窗，例如share到朋友列表页面以后，无法继续操作 需要在proguard.cfg 中，增加如下代码，您可以加到readme里面去 -keep class com.tencent.mm.opensdk.** { *; }
> 
> -keep class com.tencent.wxop.** { *; }
> 
> -keep class com.tencent.mm.sdk.** { *; }

好的，感谢

**Comment by HaddyYang** [comment]
1. android 11 适配
2. 分享类型加入MV接口

**Comment by wubaibin** [comment]
> 请各位在此留言希冀新增加的能力或需要解决的问题，我尽力处理。

ld: in /Users/wubaibin/Documents/工作区/App/RN/WechatPay/node_modules/react-native-wechat-lib/ios/libWeChatSDK.a(WechatAuthSDK.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/wubaibin/Documents/工作区/App/RN/WechatPay/node_modules/react-native-wechat-lib/ios/libWeChatSDK.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'WechatPay' from project 'WechatPay')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'WechatPay' from project 'WechatPay')

** BUILD FAILED **


The following build commands failed:
        Ld /Users/wubaibin/Library/Developer/Xcode/DerivedData/WechatPay-cwxylxrdxkxrwudqvjewnboyovjd/Build/Products/Debug-iphonesimulator/WechatPay.app/WechatPay normal (in target 'WechatPay' from project 'WechatPay')
(1 failure)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

大佬，这个问题如何解决

**Comment by bitting304** [comment]
大佬，能否把微信客服功能也加进来？跪谢

**Comment by little-snow-fox** [comment]
本库编写的时候是 react native 59，我尝试把现在代码升级到 react native 70，但似乎并不容易，出现了很多兼容性问题

**Comment by skyshocker** [comment]
请问能不能支持一下expo managed projects，写一个expo plugin，这样就不需要eject了。现在很多新的project都不会用prebuild来eject，这样不用去为了一个特定的功能去改native code。如果这个库能带一个expo plugin自动修改native code，那就完美了。谢谢。

**Comment by XionGuo37** [comment]
> 请各位在此留言希望新增的功能或者需要解决的问题，我尽量处理。

[https://github.com/little-snow-fox/react-native-wechat-lib/issues/214](url)，大佬这个如何解决

**Comment by eellkk** [comment]
留给作者的时间不多了。

**Comment by little-snow-fox** [comment]
3.0.0 版本已发布，但目前为 alpha 版，只对 Android 部分功能进行了测试，至于 IOS 版本，因为最近没有 IOS 应用在开发，所以需要申请 IOS 个人开发者后才能进行测试

**Comment by little-snow-fox** [comment]
3.0.0 完全迁移到 react 70，并且提供了[样例工程](https://github.com/little-snow-fox/react-native-wechat-lib/tree/master/example) ，样例工程里面的功能会逐步添加，也希望各位大佬能积极提交PR

**Comment by themez** [comment]
新版本还需要这样配置吗：https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-android.md

**Comment by little-snow-fox** [comment]
> 新版本还需要这样配置吗：https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-android.md

有一半配置已经写到库的配置文件里，我尝试一下能不能全部写到模块的配置文件中，节省你们的配置过程

**Comment by little-snow-fox** [comment]
> 新版本还需要这样配置吗：https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-android.md

安卓文档更新了，并且在样本工程里把需要额外添加配置的地方都做了标记

**Comment by iamyang1314** [comment]
有拉起微信客服的功能吗？

**Comment by jameszhan02** [comment]
> 请问能不能支持一下expo managed projects，写一个expo plugin，这样就不需要eject了。现在很多新的project都不会用prebuild来eject，这样不用去为了一个特定的功能去改native code。如果这个库能带一个expo plugin自动修改native code，那就完美了。谢谢。

最近我在做这方面的，公司项目结束了我准备整理一下，公司项目的本体已经用plugin 集成完成了争取明年一月份提一个PR把
@little-snow-fox  不知道大佬有没有时间看

**Comment by skyshocker** [comment]
> > 请问能不能支持一下expo managed projects，写一个expo plugin，这样就不需要eject了。现在很多新的project都不会用prebuild来eject，这样不用去为了一个特定的功能去改native code。如果这个库能带一个expo plugin自动修改native code，那就完美了。谢谢。
> 
> 
> 
> 最近我在做这方面的，公司项目结束了我准备整理一下，公司项目的本体已经用plugin 集成完成了争取明年一月份提一个PR把
> 
> @little-snow-fox  不知道大佬有没有时间看

非常给力的feature。有expo plugin就太好了。就是因为这个我们项目一直没有接入微信。如有需要我可以帮忙测试plugin。谢谢

**Comment by XHFkindergarten** [comment]
> > 请问能不能支持一下expo managed projects，写一个expo plugin，这样就不需要eject了。现在很多新的project都不会用prebuild来eject，这样不用去为了一个特定的功能去改native code。如果这个库能带一个expo plugin自动修改native code，那就完美了。谢谢。
> 
> 最近我在做这方面的，公司项目结束了我准备整理一下，公司项目的本体已经用plugin 集成完成了争取明年一月份提一个PR把 @little-snow-fox 不知道大佬有没有时间看

蹲

**Comment by xxxxxccc** [comment]
> > 请问能不能支持一下expo managed projects，写一个expo plugin，这样就不需要eject了。现在很多新的project都不会用prebuild来eject，这样不用去为了一个特定的功能去改native code。如果这个库能带一个expo plugin自动修改native code，那就完美了。谢谢。
> 
> 最近我在做这方面的，公司项目结束了我准备整理一下，公司项目的本体已经用plugin 集成完成了争取明年一月份提一个PR把 @little-snow-fox 不知道大佬有没有时间看

求
