### ISSUE TITLE
ios sendAuthRequest There was no response

### ISSUE THREAD

**Issue by caijiami** [little-snow-fox/react-native-wechat-lib#55]
WeChat.sendAuthRequest('snsapi_userinfo','raise_funds')
                    .then(res => {
                      console.log(res)
})
                    .catch((error) => {
                      console.log(error.message)
                      Toast.fail('微信登录失败',1.5)
                    })

 "react": "16.6.3",
    "react-native": "0.58.6",
 "react-native-wechat-lib": "^1.1.16",

There is no qq to discuss

**Comment by caijiami** [comment]
@little-snow-fox

**Comment by caijiami** [comment]
No reaction and no return

**Comment by caijiami** [comment]
All other methods indicate that it is not a funcion

**Comment by caijiami** [comment]
WeChat API invoke returns false.

**Comment by hengkx** [comment]
+1

**Comment by younthu** [comment]
+1

**Comment by MrPluto** [comment]
open wechat sdk log and see what happenned

**Comment by younthu** [comment]
1. make sure you provided valid url while you registerApp

**Comment by gdchent** [comment]
+1 我按照官方文档（https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md）走了, 配置 了 lib库  info.plist设置微信拉起权限
On iOS 9+, add wechat and weixin into LSApplicationQueriesSchemes in Targets > info > Custom iOS Target Properties. Or edit Info.plist then add:
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>weixin</string>
  <string>wechat</string>
  <string>weixinULAPI</string>
</array>
If not configured, apple will prevent you from jumping to WeChat due to security permissions.
如果不配置，因为安全权限问题，苹果会阻止你跳转到微信。

**Comment by gdchent** [comment]
https://github.com/little-snow-fox/react-native-wechat-lib/issues/47
